name: TDR Run Tests
on:
  pull_request:
  push:
    branches-ignore:
      - master
      - release-*
jobs:
  test:
    uses: nationalarchives/tdr-github-actions/.github/workflows/tdr_test.yml@f4d7086babd2c5156dd483d445e4500a603d8dc4 # v.0.0.42
    permissions:
      contents: write
    with:
      repo-name: tdr-auth-utils
      test-command: |
        sbt test
    secrets:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
